[package]
name = "release-notes-rs"
version = "0.1.0"
authors = ["Travis Johnson <travis@jumprope.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.10"
semver = "0.9.0"
regex = "1"